name: language-sygus

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [ { ghc: '8.6.5', cabal: '3.0' }, { ghc: '8.10.7', cabal: '3.6' }, { ghc: '9.2.2', cabal: '3.6' }]
        test: [ test ]

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v2
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.compiler.ghc }}
        cabal-version: ${{ matrix.compiler.cabal }}

    - run: cabal update
    - run: cabal configure --enable-tests
    - run: cabal freeze
    - uses: actions/cache@v2
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: cabal-${{ runner.os }}-${{ matrix.compiler.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          cabal-${{ runner.os }}-${{ matrix.compiler.ghc }}-

    - name: Install dependencies
      run: |
        cabal install --only-dependencies
        cabal build
    - name: Build
      run: cabal build
    - name: Run tests
      run: cabal test ${{ matrix.test }}